#!/bin/sh
#
#  Script:			pt_script
#  Instance:		notify
#  %version:		1 %
#  Description:		
#  %created_by:		tomf %
#  %date_created:	Tue May 21 11:20:24 1996 %

mydate=`date`
echo COMPLETATO TSK $1 $2 $3 $4 $5 $mydate > /develop/ccm_databases/billing/lib/notify/Unix/myflag
echo export MFROMSTEP='"'$2'"'>/develop/ccm_databases/billing/lib/notify/Unix/myflag.set
echo "export MCHANGER=$3">>/develop/ccm_databases/billing/lib/notify/Unix/myflag.set
echo "export MRELEASE=$4">>/develop/ccm_databases/billing/lib/notify/Unix/myflag.set
echo "export MBUG=$5">>/develop/ccm_databases/billing/lib/notify/Unix/myflag.set
exit 0
