#!/bin/sh
#
#  Script:			pre_sqa_script
#  Instance:		notify
#  %version:		1 %
#  Description:		
#  %created_by:		tomf %
#  %date_created:	Tue May 21 11:16:43 1996 %

echo "MSG:Only called when a csrcs is going to sqa"

exit 0

