#!/bin/csh
#***********************************************************************
#*                 CheckComitverIncrementaleAlfaNumerica
#* 
#* Goal: Controllare che la comitver inserita sia alfanumericamente
#*       incrementale rispetto all'ultima patch/baseline.
#*       0 - tutto ok
#*       1 - comitver non incrementale.
#*       ATTENZIONE: esco al primo errore riscontrato.
#*
#* Parametri passati:$1 COMITVER
#*                   $2 LAST_PATCH_NUMBER
#* 
#* Autore: Luca Brizzolara - Mar 2000
#* 
#***********************************************************************

set COMITVER = $1
set last_patch_number = $2
set NUMERI = "0 1 2 3 4 5 6 7 8 9"
set ALFABETO = "0 A B C D E F G H I J K L M N O P Q R S T U V W X Y Z"

#*************************************************************
# Verifico la correttezza di numerazione della comitver
# (sempre crescente)
#*************************************************************
set base_number = `echo ${COMITVER} |awk '{ print substr($1,1,3) }'`
set version_number = `echo ${COMITVER} |awk '{ print substr($1,4,1) }'`
set version_letter = `echo ${COMITVER} |awk '{ print substr($1,5,1) }'`
set last_base_number = `echo ${last_patch_number} |awk '{ print substr($1,1,3) }'`
set last_version_number = `echo ${last_patch_number} |awk '{ print substr($1,4,1) }'`
set last_version_letter = `echo ${last_patch_number} |awk '{ print substr($1,5,1) }'`
if ( ${last_base_number} > ${base_number} ) then
  exit 1
else
  if ( ${last_base_number} == ${base_number} ) then
    if ( ${last_version_number} > ${version_number} ) then
      exit 1
    else
      if ( ${last_version_number} == ${version_number} ) then
        if (${last_version_letter} != ${version_letter} ) then
          foreach Lettera ($ALFABETO)
           if ($Lettera == ${last_version_letter} ) then
              goto Good_Chk
            endif
            if ($Lettera == ${version_letter} ) then
              exit 1
            endif
          end
        else
          exit 1
        endif
      endif
    endif
  endif
endif
Good_Chk:
exit 0

