#!/bin/csh
#***********************************************************************
#*
#*                    cpCCMfl_consegna
#*
#*
#*
#*
#* Author: Luca Brizzolara, Apr 2000
#*
#***********************************************************************

set root_dest = $1
set root_src = $2
shift
shift
while ($#argv != 0)
  set dest = "$1"
  set sep = `echo ${dest} | awk '{print gsub("/","",$1)}'`
  set rootsep = `echo ${root_dest} | awk '{print gsub("/","",$1)}'`
  set i = ${rootsep} 
  while ($i <= (${rootsep} + ${sep}))
    @ i++
    set cur_dir = `echo ${root_dest}/${dest} | cut -d/ -f1-$i`
    if !(-d ${cur_dir}) then
      mkdir ${cur_dir} 
      chmod a+w ${cur_dir} 
    endif
  end
  if (-f ${root_src}/${dest}) then
    cp -f ${root_src}/${dest} ${root_dest}/${dest}
    chmod a+w ${root_dest}/${dest}
  endif
  shift
end
