#!/bin/csh
#***********************************************************************
#*
#*                  genera_comandi_rm
#*
#*
#* Author: Brizzolara Luca 1999
#* Parametri: $1 SOURCE (directory)
#*            $2 FILE_COMANDI
#***********************************************************************

# **********************************************************************
# Set Environment Vars
# **********************************************************************

set SOURCE = $1
set FILE_COMANDI = $2

# **********************************************************************
# File system structure check
# **********************************************************************

set n = 0
while ($n != 2)
  shift
  set n = `expr $n + 1`
end


while ($#argv != 0)
  set FILE_NAME = $1
  echo "rm ${SOURCE}${FILE_NAME}" >> ${FILE_COMANDI}
  shift
end

