#!/bin/csh
#***********************************************************************
#*
#*                     PrjSchelDB_script 
#*
#* Goal: Creare un nuovo progetto, vuoto, con i folder ed i vari 
#*       ambienti. Crea anche il folder per SVI!!!
#*
#* Parameters: $1 nome del progetto (tre lettere)
#*
#* Author: Luca Brizzolara 1999
#*
#***********************************************************************

# **********************************************************************
# Actions check
# **********************************************************************
if (`echo $1 | awk '{print length($1)}'` != 3) then  
  echo Prj $1 MUST be 3 chars
  exit 0
endif

# **********************************************************************
# Set Environment Vars
# **********************************************************************
set CCM45_DB = "/usr/CONT_SRV/ccmdb/DB_GPM"
set CCM45_DBlog = "${CCM45_DB}/lib/notify/log"
set WA_ROOT  = "/usr/CONT_SRV/ccm_wa/DB_GPM"
set DB_Prj   = `echo $1 | awk '{print toupper($1)}'`

setenv CCM_ADDR `ccm start -m -q -nogui -r build_mgr -d ${CCM45_DB}`
set fnd = `ccm query -t project -n ${DB_Prj} -v FIX`
if ( $#fnd != 0) then
  echo " "
  echo Abort: Could not create ${DB_Prj}. Found ${DB_Prj} Project into ${CCM45_DB} Continuus DataBase.
  echo " "
  ccm stop
  exit 0
endif
# SQA, PRD env creating...
set Env = `printf "%s\n%s" PRD FIX`
set Envnum = `echo $#Env` 
set j = 0
set i = 1
while ($i < ${Envnum})
  @ j++
  @ i++
  ccm co -c "Ambiente di integrazione $Env[$i] DB_GPM" -p ${DB_Prj}~$Env[$j] -versions $Env[$j]\:$Env[$i]
  ccm work_area -wa -setpath $WA_ROOT ${DB_Prj}~$Env[$i]
  ccm query -t project -name ${DB_Prj} -v $Env[$i] 
  ccm attr -m owner -v cm_sesi @1
  ccm attr -m baseline -v "${DB_Prj}~$Env[$i]" @1
  ccm set role ccm_admin
  ccm del `ccm reconf_prop -sh tasks ${DB_Prj}~$Env[$i] -u -f "%objectname"`
  ccm set role build_mgr 
  set folder_id = `ccm folder -cr -n "Consegne ${DB_Prj} pronte per $Env[$i]" -w Build_Manager -us All -q`
  ccm reconf_prop -add -folders ${folder_id} ${DB_Prj}~$Env[$i]
  ccm query -t folder -name ${folder_id}
  ccm attr -c folder_subsys -t string -v ${DB_Prj}~$Env[$i] @1
end
# Env created ...
ccm stop
