#!/bin/csh
# **********************************************************************
# Set Environment Vars
# **********************************************************************

set SWD_ROOT = "/usr/CONT_SRV/SWD_FIL"
set CCM45_DB = "/usr/CONT_SRV/ccmdb/DB_FIL"
set EXE_DIR = "${CCM45_DB}/lib/notify/Unix"

clear

if !($1 == CSU || $1 == SQA || $1 == PRD) then
  echo " " 
  echo Errore: Immetti il parametro relativo a  CSU o SQA o PRD. 
  echo " " 
  exit 1
endif

echo " " 
echo Creazione ZIP OS2 per EDM in corso...
echo " " 

${EXE_DIR}/ccmcpkzip_script ${SWD_ROOT}/$1

